// Map iOS SF Symbol names to an emoji so iconBreakdown slides show a real glyph
// on web (no icon font needed). Keyword-matched, most specific first.
const RULES: [RegExp, string][] = [
  [/graduationcap/, '🎓'],
  [/creditcard/, '💳'],
  [/banknote|dollarsign|money|cash/, '💵'],
  [/chart\.pie/, '📈'],
  [/chart|xyaxis|uptrend/, '📊'],
  [/calendar/, '📅'],
  [/clock|alarm|timer|stopwatch|hourglass/, '⏰'],
  [/bell/, '🔔'],
  [/checkmark\.shield|shield\.checkmark|lock\.shield/, '🛡️'],
  [/exclamationmark|warning|triangle\.fill/, '⚠️'],
  [/shield/, '🛡️'],
  [/checkmark|seal/, '✅'],
  [/xmark|cross\.circle/, '❌'],
  [/cross\.case|cross\.fill|medical|heart\.text|stethoscope|pills|bandage/, '🏥'],
  [/heart/, '❤️'],
  [/star/, '⭐'],
  [/flame/, '🔥'],
  [/bolt\.slash/, '🔌'],
  [/bolt/, '⚡'],
  [/lightbulb/, '💡'],
  [/brain/, '🧠'],
  [/book/, '📚'],
  [/doc|note|text|paper|newspaper/, '📄'],
  [/folder/, '📁'],
  [/briefcase/, '💼'],
  [/building\.columns|bank/, '🏛️'],
  [/building|house|home/, '🏠'],
  [/cart|bag/, '🛒'],
  [/gift/, '🎁'],
  [/airplane/, '✈️'],
  [/car\.|car$|fuelpump/, '🚗'],
  [/bus/, '🚌'],
  [/bicycle/, '🚲'],
  [/globe|map/, '🌍'],
  [/envelope|mail/, '✉️'],
  [/phone|iphone|desktopcomputer|laptopcomputer/, '📱'],
  [/camera/, '📷'],
  [/headphones|music|speaker/, '🎧'],
  [/gamecontroller/, '🎮'],
  [/person\.2|person\.3|figure\.2|people|group/, '👥'],
  [/person|figure|face/, '🧑'],
  [/hand\.raised/, '✋'],
  [/hands|handshake|sparkles/, '🤝'],
  [/lock\.open/, '🔓'],
  [/lock|key/, '🔒'],
  [/eye\.slash/, '🙈'],
  [/eye/, '👁️'],
  [/flag/, '🚩'],
  [/target|scope|binoculars/, '🎯'],
  [/drop|water/, '💧'],
  [/leaf|tree|seedling/, '🌱'],
  [/fork\.knife|cup|takeout/, '🍽️'],
  [/backpack/, '🎒'],
  [/hammer|wrench|gearshape|gear/, '🛠️'],
  [/arrow\.up\.arrow\.down|arrow\.left\.arrow\.right|arrow\.2|squarepath|circlepath/, '🔄'],
  [/arrow\.up/, '⬆️'],
  [/arrow\.down/, '⬇️'],
  [/plus/, '➕'],
  [/minus/, '➖'],
  [/percent/, '％'],
  [/bubble|message|text\.bubble/, '💬'],
]

export function sfEmoji(name?: string): string {
  if (!name) return '◆'
  for (const [re, emoji] of RULES) if (re.test(name)) return emoji
  return '💵' // finance-y default
}
